# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: backend
build:
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: asia-east1-docker.pkg.dev/shawnho-demo-2023/shawnho-demo-2023/java-guestbook-restful
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      jib:
        project: backend
      context: ../
manifests:
  rawYaml:
    - cloudrun-manifests/*
deploy:
  cloudrun:
    projectid: shawnho-demo-2023
    region: asia-east1
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: dockerfile
  build:
    artifacts:
      - image: java-guestbook-backend
        context: .
        