apiVersion: v1
kind: Service
metadata:
  name: java-guestbook-mongodb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: java-guestbook
    tier: db
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: java-guestbook
    tier: db
