################################################################################
# WARNING: This MongoDB deployment is not suitable for production as the data is
# not persistently stored and will go away every time the Pod restarts. Consider
# using a Helm chart that provisions a StatefulSet instead of Deployment.
################################################################################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-guestbook-mongodb
  labels:
    app: java-guestbook
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-guestbook
      tier: db
  template:
    metadata:
      labels:
        app: java-guestbook
        tier: db
    spec:
      containers:
      - name: mongo
        image: mongo:4
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "mongo-data"