apiVersion: v1
kind: Service
metadata:
  name: java-guestbook-mongodb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: java-guestbook
    tier: db
spec:
  type: LoadBalancer
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
    - name: metrics
      port: 9216
      targetPort: 9216
  selector:
    app: java-guestbook
    tier: db
