apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: mongodb-monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: java-guestbook
      tier: db
