apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend # this service will be created in Cloud Run via Skaffold
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/vpc-access-connector: projects/shawnho-demo-2023/locations/asia-east1/connectors/asia-east1-serverless
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: myimage
        ports:
        - name: http1
          containerPort: 8080
        env:
          - name: MYPORT
            value: "8080"
          - name: GUESTBOOK_DB_ADDR
            value: "10.2.0.4:27017"
          # This environment variable enables debugging support for the container.
          # Remove this to disable the debug build.
          - name: JAVA_TOOL_OPTIONS
            value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y