apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-guestbook-backend
  labels:
    app: java-guestbook
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-guestbook
      tier: backend
  template:
    metadata:
      labels:
        app: java-guestbook
        tier: backend
    spec:
      initContainers:
      - name: init-db-ready
        image: mongo:4
        command: ['/bin/sh', '-c']
        args:
          - echo "Waiting for mongodb at java-guestbook-mongodb:27017 to go live before the BE..."; 
          - until (mongo --host java-guestbook-mongodb:27017 >/dev/null) do echo "Waiting for connection for 2 sec."; sleep 2; done
      containers:
      - name: backend
        image: asia-east1-docker.pkg.dev/shawnho-demo-2023/shawnho-demo-2023/java-guestbook-backend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_DB_ADDR
          value: "java-guestbook-mongodb:27017"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://ubuntu0.default.svc:4317
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "1.0"